@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODAzY2JmNjA5OWNjZTk5Y2Q2MzJkMzEiLCJpYXQiOjE3NDUzNDE5MzIsImV4cCI6MTc0NTM1OTkzMn0.coqCW9_w06Ddy76aAYrqzaEFyC6c0V4M5M5s3Hk42T4

### Register a new user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Kevin",
  "email": "kevin@example.com",
  "password": "yourPassword"
}

### Login with registered user
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "kevin@example.com",
  "password": "yourPassword"
}

### Add Expense
POST http://localhost:5000/api/expenses
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "amount": 22.50,
  "description": "Snacks",
  "subcategory": "Food",
  "date": "2025-01-20T12:00:00.000Z"
}

### Create a new subcategory
POST http://localhost:5000/api/subcategories
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "categoryType": "expense",
  "name": "Home Improvement",
  "budget": 200.00
}

### POST TRANSACTION
POST http://localhost:5000/api/transactions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "subcategory": "6807495561d8ab719844c1ae",
  "amount": 212.99,
  "date": "2025-04-21",
  "description": "Air Compressor",
  "recurring": false
}

### Set or Update Budget
POST http://localhost:5000/api/budget
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN_HERE

{
  "category": "expenses",
  "amount": 1200
}