### Register a new user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Kevin",
  "email": "kevin@example.com",
  "password": "yourPassword"
}

### Login with registered user
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "kevin@example.com",
  "password": "yourPassword"
}
