# fly.toml app configuration file generated for mern-expense-tracker-icy-frog-6846 on 2025-05-06T10:18:59-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mern-expense-tracker-icy-frog-6846'
primary_region = 'den'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
