app = "mern-expense-tracker"

[build]
    dockerfile = "server/Dockerfile"
    context = "server"

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[processes]
  app = "node server/index.js"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]  # 👈 This links the service to the "app" process

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
